server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5433/product_service
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
